PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xerl: <http://www.xerleben.de/schema/2.0_1#>
PREFIX xplan5: <http://www.xplanung.de/xplangml/5/0#>
PREFIX semgis: <http://www.semgis.de/geodata#> 
SELECT ?minClearance ?the_geom WHERE {
 ?geom geo:asWKT ?the_geom .
 BIND(geo:ST_MinimumClearance(?the_geom) AS ?minClearance) 
}